modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      # valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 401]  # Defaults to 2xx
      method: GET
      preferred_ip_protocol: "ip4"
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false

  # http_post_2xx:
  #   prober: http
  #   timeout: 5s
  #   http:
  #     method: POST
  #     valid_status_codes: []

  # tcp_connect:
  #   prober: tcp
  #   timeout: 5s

  # icmp:
  #   prober: icmp
  #   timeout: 5s
  #   icmp:
  #     preferred_ip_protocol: "ip4"
